# Generated by Django 3.1.1 on 2020-11-19 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ieat', '0008_auto_20201119_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.CharField(max_length=150),
        ),
    ]
